## Numpy의 주요 함수들(1)


In [1]:
# 우선 실행해주세요
import numpy as np

### Numpy Broadcasting
---

#### 넘파이의 브로드캐스팅의 규칙

1. 두 배열의 차원이 다르면 작은 쪽에 padding이 되어 배열의 크기가 큰 쪽에 맞춰집니다.
    
예시) 
```python
(6, 3, 2) + (3, 2) >> (6, 3, 2)
# 차원이 적은 d가 차원이 큰 c에 맞춰집니다.
```
    
2. 두 배열의 차원이 모두 다르고 하나의 배열의 크기가 1이면, 해당 배열에 padding한 후 계산합니다.

예시)
```python
(6, 1) + (6) >> (6, 6)
```

#### 브로드캐스팅의 이점

    규칙 1의 연산을 보면 마치 shape가 (3,2)인 array가 (6,3,2)로 늘어난 후에 연산이 진행되는 것 처럼 보이지만, 실제로는 (3,2)인 array가 (6,3,2)인 array에 벡터형식으로 적용되어 연산이 **동시에** 진행됩니다. 
    
    언뜻 보면 큰 차이가 없어보이지만, (3,2) array가 (6,3,2) array로 늘어나지 않는 점에서 memory의 이득이 있고, 벡터형식으로 동시에 적용된다는 점에서 연산의 반복을 하지 않음에서 오는 이득이 있습니다

---

## 문제 1. Broadcasting에 대한 이해

* array들의 `shape`를 보고, 연산이 되지 않거나, 결과가 틀린 것들을 모두 골라주세요

```python
(a) (8, 7, 3) + (3)
(b) (3) + (4)
(c) (15, 3, 5) + (3, 5)
(d) (12, 8, 3) + (8, 1, 1)
(e) (12, 8, 3) + (8, 1, 1) = (12, 8, 3)
(f) (12, 8, 3) + (12, 8, 1)
(g) (8, 1, 9, 1) + (4, 1, 6)
(h) (2, 1) + (8, 4, 3)
(i) (2, 1) + (8, 4, 3) = (8, 4, 3)
(j) (3, 1, 1) + (2, 1)
(k) (3, 1, 1) + (2, 1) = (3, 2, 1)
```

* 정답은 다음과 같이 `list`에 담아주세요
    ```python
    answer1 = ['a', 'b', 'c']
    ```

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 정답은 `answer1`에 담아주세요

In [2]:
answer1 = ['b', 'd', 'e', 'h', 'i']

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [3]:
assert 'answer1' in globals(), "결과를 answer1이라는 변수에 담아주세요!, answer1의 값을 보고 평가합니다."

A = [chr(98), chr(100), chr(101), chr(104), chr(105)]

assert isinstance(answer1, list), "정답을 'list'에 담아주세요"
assert len(A) == len(answer1), "갯수가 맞지 않습니다"

A.sort()
answer1.sort()
for _A,_answer in zip(A, answer1):
    assert _answer == _A, "답이 틀립니다! broadcasting 규칙에 맞는지 다시 확인해보세요!"
else:
    print("정답입니다!!!!")


정답입니다!!!!


## 문제 2. 세균의 생존지수 측정 실험

한 연구실에서

$$세균의~생존지수 = \exp^{상온에서~세균의~증식속도}~\times~습도~\times~k~(k=23.78)$$

이라는 가설을 입증하기 위한 실험을 진행하려고 합니다.

* 세균에 따른 상온에서의 증식속도

| 세균 | A | B | C | D | E | F | G |
|  ----   | --- |---| --- | --- | --- | --- | --- |
| 증식속도 | 0.83 | 0.72 | 0.93 | 1.23 | 0.36 | 2.31 | 1.67 |

* 실험하기 위한 습도 case

| case | 1 | 2 | 3 | 4 | 5 |
|  ----   | --- |---| --- | --- | --- |
| 습도 | 20% | 40% | 50% | 60% | 80% |

<br>

* 가설이 맞다는 가정하에, 위의 두 표를 이용하여 `세균의 생존지수`를 담고 있는 표를 만들어주세요

| 생존지수 | 20% | 40% | 50% | 60% | 80% |
| --- | --- |---| --- | --- | --- |
| A | 24.1073148 | 29.44474079 | 32.54147121 | 35.96388761 | 43.92639152 |
| B | 20.91236946 | 25.54242574 | 28.22874611 | 31.19758925 | 38.10482156 |
| C | 27.01181056 | 32.99229992 | 36.46213039 | 40.29688612 | 49.21872785 |
| D | 35.72529783 | 43.63497731 | 48.22410794 | 53.29588164 | 65.09573683 |
| E | 10.45618473 | 12.77121287 | 14.11437305 | 15.59879463 | 19.05241078 |
| F | 48.50507917 | 59.24423749 | 65.47500833 | 72.36107507 | 88.38201668 |

정답 >>>
```python
np.array([[24.1073148 , 29.44474079, 32.54147121, 35.96388761, 43.92639152],
       [20.91236946, 25.54242574, 28.22874611, 31.19758925, 38.10482156],
       [27.01181056, 32.99229992, 36.46213039, 40.29688612, 49.21872785],
       [35.72529783, 43.63497731, 48.22410794, 53.29588164, 65.09573683],
       [10.45618473, 12.77121287, 14.11437305, 15.59879463, 19.05241078],
       [48.50507917, 59.24423749, 65.47500833, 72.36107507, 88.38201668]])
```

In [4]:
# 우선 실행해주세요
speed = np.array([0.83, 0.72, 0.93, 1.23, 0.36, 1.67])
humidity = np.array([0.2, 0.4, 0.5, 0.6, 0.8])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 정답은 `answer2`에 담아주세요

In [5]:
speed = speed.reshape(-1,1)
answer2 = speed * np.exp(humidity) * 23.78

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [6]:
from numpy.testing import assert_array_almost_equal

assert 'answer2' in globals(), "결과를 answer2라는 변수에 담아주세요!, answer2의 값을 보고 평가합니다."

A = np.array([[24.1073148 , 29.44474079, 32.54147121, 35.96388761, 43.92639152],
       [20.91236946, 25.54242574, 28.22874611, 31.19758925, 38.10482156],
       [27.01181056, 32.99229992, 36.46213039, 40.29688612, 49.21872785],
       [35.72529783, 43.63497731, 48.22410794, 53.29588164, 65.09573683],
       [10.45618473, 12.77121287, 14.11437305, 15.59879463, 19.05241078],
       [48.50507917, 59.24423749, 65.47500833, 72.36107507, 88.38201668]])

assert_array_almost_equal(A, answer2,decimal=3, err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 3. 시그모이드(로지스틱) 함수

**Sigmoid(Logistic) 함수**란 S자와 유사한 완만한 커브형태를 보이는 함수입니다. Sigmoid 함수는 모든 실수 입력 값을 `0`에서 `1` 사이의 미분 가능한 수로 변환하는 특징을 갖습니다. 이러한 특징으로 인해 후에 Logistic Regression과 같은 분류 문제에서 미분이 되지 않는 지점의 값들을 미분 가능하도록 만들어 주고 싶을 때 사용합니다. 또한 sigmoid의 반환 값은 `0`에서 `1`사이의 확률형태이기 때문에 결과를 확률로 해석할 때 유용합니다.

시그모이드 함수의 수식은 다음과 같습니다.

$$Sigmoid~=~\frac{1}{1+e^{-z}}$$

* 데이터를 입력했을 때 시그모이드 함수의 결과를 반환하는 함수를 만들어주세요


* 참고 : 시그모이드 함수의 그래프

![Imgur](https://i.imgur.com/MiZVuUg.png?1)

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 메소드 이름은 `simgoid`로 해주세요

In [7]:
def sigmoid(input_array):
    ############
    # CODE HERE!
    ############
    return 1.0/(1+np.exp(input_array))

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [8]:
from numpy.testing import assert_array_almost_equal

assert 'sigmoid' in globals(), "메소드 명을 sigmoid로 해주세요"
f = sigmoid
assert_array_almost_equal(f([1,2,3,4]),np.array([0.26894142, 0.11920292, 0.04742587, 0.01798621]),decimal=7,
                          err_msg="\n\ninput_array가 [1,2,3,4]일 때, 정답은 \
                          \narray([0.26894142, 0.11920292, 0.04742587, 0.01798621])\n입니다. 코드를 다시 확인해주세요")
assert_array_almost_equal(f([8,9]),np.array([0.00033535, 0.00012339]),decimal=7,
                          err_msg="\n\ninput_array가 [8,9]일 때, 정답은 \
                          \narray([0.00033535, 0.00012339])\n입니다. 코드를 다시 확인해주세요")
assert_array_almost_equal(f([2.2, 8.8]),np.array([0.09975049, 0.00015071]),decimal=7,
                          err_msg="\n\ninput_array가 [2.2,8.8]일 때, 정답은 \
                          \narray([0.26894142, 0.11920292, 0.04742587, 0.01798621])\n입니다. 코드를 다시 확인해주세요")
assert_array_almost_equal(f([3.38, 4.92]),np.array([0.03292639, 0.00724624]),decimal=7,
                          err_msg="\n\ninput_array가 [3.38,4.92]일 때, 정답은 \
                          \narray([0.03292639, 0.00724624])\n입니다. 코드를 다시 확인해주세요")

print("정답입니다!!")

정답입니다!!


## 문제 4. 극 좌표계

* 좌표계에는 크게 2가지가 있는데, 하나는 우리가 흔히 쓰는 X,Y축으로 표현되는 직교 좌표계이고. 다른 하나는 각도와 거리로 표현되는 극 좌표계가 있습니다. 직교좌표계에서 극좌표계로 바꾸기 위해서는 아래와 같이 풀면 됩니다.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Polar_to_cartesian.svg/460px-Polar_to_cartesian.svg.png)

$$x = r*cos\varphi \\ y = r*sin\varphi$$

아래와 같이 극좌표값이 주어졌을 때, 이를 직교좌표값으로 변환해주세요.

| $r$ | $\varphi$ |
|----|----|
| 1  | 0.1 |
| 1  | 0.5 |
| 2  | 0.7 |
| 2  | 1.2 |
| 3  | 1.5 |
| 3  | 2.0 |
| 4  | 2.8 |
| 4  | 3.1 |

In [9]:
# 우선 실행해주세요
coords = np.array([
    [1,0.1],
    [1,0.5],
    [2,0.7],
    [2,1.2],
    [3,1.5],
    [3,2.0],
    [4,2.8],
    [4,3.1]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

In [10]:
x = coords[:,0]*np.cos(coords[:,1])
y = coords[:,0]*np.sin(coords[:,1])

answer4 = np.stack([x,y],axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [11]:
from numpy.testing import assert_array_almost_equal

assert 'answer4' in globals(), "결과를 answer4라는 변수에 담아주세요!, answer4의 값을 보고 평가합니다."

A = np.array([[ 0.99500417,  0.09983342],
       [ 0.87758256,  0.47942554],
       [ 1.52968437,  1.28843537],
       [ 0.72471551,  1.86407817],
       [ 0.21221161,  2.99248496],
       [-1.24844051,  2.72789228],
       [-3.76888936,  1.3399526 ],
       [-3.9965406 ,  0.16632265]])

assert_array_almost_equal(A,answer4,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


> 문제 5번, 문제 6번, 문제 7번은 table-1을 참고하여 풀어주세요!

#### Table-1) 중간고사, 기말고사 학생들의 성적표

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [12]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

현재 데이터의 shape는 (2,6,5)로, 

* 첫번째 축 : 중간 / 기말
* 두번째 축 : 학생 번호 
* 세번째 축 : 과목

으로 구성되어 있다.

## 문제 5. 배열 전체에 연산 적용하기
* 모든 점수의 범위가 0~1이 될수 있도록, 전체 점수를 100으로 나누어주세요 

In [13]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer5`에 담아주세요

In [14]:
answer5 = scores / 100

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [15]:
from numpy.testing import assert_array_equal

assert 'answer5' in globals(), "결과를 answer5라는 변수에 담아주세요!, answer5의 값을 보고 평가합니다."

A = np.array([[[0.8 , 0.92, 0.7 , 0.65, 0.92],
        [0.91, 0.75, 0.9 , 0.68, 0.85],
        [0.86, 0.76, 0.42, 0.72, 0.88],
        [0.77, 0.92, 0.52, 0.6 , 0.8 ],
        [0.75, 0.85, 0.85, 0.92, 0.95],
        [0.96, 0.9 , 0.95, 0.81, 0.72]],

       [[0.85, 0.95, 0.9 , 0.66, 0.93],
        [0.93, 0.7 , 0.8 , 0.6 , 0.81],
        [0.89, 0.78, 0.55, 0.75, 0.8 ],
        [0.8 , 0.94, 0.59, 0.72, 0.9 ],
        [0.7 , 0.82, 0.81, 0.95, 0.72],
        [0.9 , 0.76, 0.93, 0.82, 0.89]]])

assert_array_equal(A, answer5, 
               err_msg="\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요\n".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 6. 같은 크기의 Array 간 사칙연산

* 중간고사와 기말고사의 합산 성적을 학생별/과목별로 구해주세요

정답 >>> 
```python
np.array([[165, 187, 160, 131, 185],
    [184, 145, 170, 128, 166],
    [175, 154,  97, 147, 168],
    [157, 186, 111, 132, 170],
    [145, 167, 166, 187, 167],
    [186, 166, 188, 163, 161]])
```

In [16]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer6`에 담아주세요

In [17]:
answer6 = scores[0] + scores[1]

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [18]:
from numpy.testing import assert_array_equal

assert 'answer6' in globals(), "결과를 answer6이라는 변수에 담아주세요!, answer6의 값을 보고 평가합니다."

A = np.array([[165, 187, 160, 131, 185],
[184, 145, 170, 128, 166],
[175, 154,  97, 147, 168],
[157, 186, 111, 132, 170],
[145, 167, 166, 187, 167],
[186, 166, 188, 163, 161]])

assert_array_equal(A, answer6,"\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 7. 다른 크기의 Array 간 사칙연산

* 각 과목별로 가중치가 다르다. 가중치 행렬은 아래와 같고, 가중치를 적용한 점수를 구해봅시다.


| 국어 | 영어 | 수학 | 사회 | 과학 |
|---|---|---|---| ---|
| 0.3 | 0.2 | 0.5 | 0.2 | 0.2 |

In [19]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
weights = np.array([0.3,0.2,0.5,0.2,0.2]) # 가중치 행렬
scores, weights

(array([[[80, 92, 70, 65, 92],
         [91, 75, 90, 68, 85],
         [86, 76, 42, 72, 88],
         [77, 92, 52, 60, 80],
         [75, 85, 85, 92, 95],
         [96, 90, 95, 81, 72]],
 
        [[85, 95, 90, 66, 93],
         [93, 70, 80, 60, 81],
         [89, 78, 55, 75, 80],
         [80, 94, 59, 72, 90],
         [70, 82, 81, 95, 72],
         [90, 76, 93, 82, 89]]]), array([0.3, 0.2, 0.5, 0.2, 0.2]))

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer7`에 담아주세요

In [20]:
answer7 = weights * scores

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [21]:
from numpy.testing import assert_array_almost_equal

assert 'answer7' in globals(), "결과를 answer7이라는 변수에 담아주세요!, answer7의 값을 보고 평가합니다."

A = np.array([[[24. , 18.4, 35. , 13. , 18.4],
        [27.3, 15. , 45. , 13.6, 17. ],
        [25.8, 15.2, 21. , 14.4, 17.6],
        [23.1, 18.4, 26. , 12. , 16. ],
        [22.5, 17. , 42.5, 18.4, 19. ],
        [28.8, 18. , 47.5, 16.2, 14.4]],

       [[25.5, 19. , 45. , 13.2, 18.6],
        [27.9, 14. , 40. , 12. , 16.2],
        [26.7, 15.6, 27.5, 15. , 16. ],
        [24. , 18.8, 29.5, 14.4, 18. ],
        [21. , 16.4, 40.5, 19. , 14.4],
        [27. , 15.2, 46.5, 16.4, 17.8]]])

assert_array_almost_equal(A, answer7,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


> 문제 8번, 9번은 지난 exercise1에 있던 예제들입니다. list가 아닌 numpy로 풀어보세요!

#### table-2) 2012년~2018년 삼성전자 분기별 매출

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 |
| 2018년 | 60.56 | 58.48 | 65.46 | 59.27 |

## 문제 8. 평균 대비 매출
* 전체 매출의 평균과 각 매출이 얼마나 차이나는지 표로 만들어주세요
    
    `평균 대비 매출` = `매출` - `전체 매출의 평균`


* 매출의 총합은 `numpy_array.sum()`을 사용해 구해주세요!

정답 >>> 
```python
np.array([[-9.11857143, -6.78857143, -2.20857143,  1.67142857],
       [-1.51857143,  3.07142857,  4.69142857,  4.89142857],
       [-0.70857143, -2.03857143, -6.93857143, -1.65857143],
       [-7.26857143, -5.84857143, -2.70857143, -1.06857143],
       [-4.60857143, -3.44857143, -6.56857143, -1.05857143],
       [-3.83857143,  7.60142857,  7.66142857, 11.59142857],
       [ 6.17142857,  4.09142857, 11.07142857,  4.88142857]])
```

In [22]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer8`에 담아주세요

In [23]:
sales_sum = sales.sum()
average_sales = sales_sum / (len(sales) * len(sales[0]))
answer8 = sales - average_sales

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [24]:
from numpy.testing import assert_array_almost_equal

assert 'answer8' in globals(), "결과를 answer8이라는 변수에 담아주세요!, answer8의 값을 보고 평가합니다."

A = np.array([[-9.11857143, -6.78857143, -2.20857143,  1.67142857],
       [-1.51857143,  3.07142857,  4.69142857,  4.89142857],
       [-0.70857143, -2.03857143, -6.93857143, -1.65857143],
       [-7.26857143, -5.84857143, -2.70857143, -1.06857143],
       [-4.60857143, -3.44857143, -6.56857143, -1.05857143],
       [-3.83857143,  7.60142857,  7.66142857, 11.59142857],
       [ 6.17142857,  4.09142857, 11.07142857,  4.88142857]])

assert_array_almost_equal(A, answer8,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 9. 전반기 대비 후반기 매출
* 각 연도별로 `전반기`(1분기, 2분기)에 비해 `후반기`(3분기, 4분기)의 매출이 어떻게 변했는지를 표로 만들어주세요

    `전반기 대비 후반기 매출` = `후반기 총 매출` - `전반기 총 매출`

정답 >>> 
```python
np.array([15.37,  8.03, -5.85,  9.34,  0.43, 15.49,  5.69])
```

* 힌트 : 전반기에 비해 **후반기의 매출**이 어떻게 변했는지가 문제입니다.

In [25]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer9`에 담아주세요

In [26]:
first_half = sales[:, 0] + sales[:, 1]
second_half = sales[:, 2] + sales[:, 3]
answer9 = second_half - first_half

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [27]:
from numpy.testing import assert_array_almost_equal

assert 'answer9' in globals(), "결과를 answer9라는 변수에 담아주세요!, answer9의 값을 보고 평가합니다."

A = np.array([15.37,  8.03, -5.85,  9.34,  0.43, 15.49,  5.69])

assert_array_almost_equal(A, answer9,decimal=2,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 10. 2012년도 대비 매출 성장

* 회사의 2012년도 대비 매출 성장을 담고 있는 표를 만들어주세요
    
    `2012년도 대비 매출 성장` = `해당 년도 매출` - `2012년도 매출`
    
정답 >>>
```python
np.array([[ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 7.6 ,  9.86,  6.9 ,  3.22],
       [ 8.41,  4.75, -4.73, -3.33],
       [ 1.85,  0.94, -0.5 , -2.74],
       [ 4.51,  3.34, -4.36, -2.73],
       [ 5.28, 14.39,  9.87,  9.92],
       [15.29, 10.88, 13.28,  3.21]])
```

In [28]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer10`에 담아주세요

In [29]:
first_year_sales = sales[0]
sales_growth = sales - first_year_sales
answer10 = sales_growth

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [30]:
from numpy.testing import assert_array_almost_equal

assert 'answer10' in globals(), "결과를 answer10이라는 변수에 담아주세요!, answer10의 값을 보고 평가합니다."

A = np.array([[ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 7.6 ,  9.86,  6.9 ,  3.22],
       [ 8.41,  4.75, -4.73, -3.33],
       [ 1.85,  0.94, -0.5 , -2.74],
       [ 4.51,  3.34, -4.36, -2.73],
       [ 5.28, 14.39,  9.87,  9.92],
       [15.29, 10.88, 13.28,  3.21]])

assert_array_almost_equal(A, answer10,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


> 문제 11번, 문제 12번은 table-3을 참고하여 풀어주세요!

#### table-3) 득점순위에 따른 리그별 축구선수들의 데이터

* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

## 문제 11. 공격포인트

* `공격포인트`는 `골`과 `도움`을 합친(+) 데이터입니다. table-3에 `공격포인트`열을 추가한 표를 만들어주세요


* 변경과정

![Imgur](https://i.imgur.com/2rZRtKz.png)

정답 >>>

```python
np.array([[[ 22,   1,  87,  42,  36,  23],
        [ 22,   5,  93,  40,  36,  27],
        [ 22,   8, 135,  64,  38,  30],
        [ 21,   8, 117,  43,  33,  29],
        [ 16,  15,  94,  43,  37,  31],
        [ 12,   6,  74,  29,  31,  18]],

       [[ 36,  13, 171,  88,  34,  49],
        [ 21,   6, 111,  58,  33,  27],
        [ 21,   6, 104,  45,  36,  27],
        [ 20,   6,  70,  31,  27,  26],
        [ 19,   0,  80,  40,  32,  19],
        [ 15,   8, 112,  46,  37,  23]],

       [[ 26,   8, 119,  70,  37,  34],
        [ 23,   7,  92,  58,  37,  30],
        [ 22,   0,  91,  60,  37,  22],
        [ 21,   6, 136,  77,  31,  27],
        [ 17,   3,  92,  59,  35,  20],
        [ 16,   9,  76,  45,  35,  25]]])
```

In [31]:
## 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

player_data = np.stack((england, spain, italy))
player_data

array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer11`에 담아주세요

In [32]:
goals = player_data[:,:,0]
assists = player_data[:,:,1]
attack_point = goals + assists
reshaped_attack_point = attack_point.reshape(3,6,1)
answer11 = np.concatenate((player_data, reshaped_attack_point), axis=-1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [33]:
from numpy.testing import assert_array_almost_equal

assert 'answer11' in globals(), "결과를 answer11이라는 변수에 담아주세요!, answer11의 값을 보고 평가합니다."

A = np.array([[[ 22,   1,  87,  42,  36,  23],
        [ 22,   5,  93,  40,  36,  27],
        [ 22,   8, 135,  64,  38,  30],
        [ 21,   8, 117,  43,  33,  29],
        [ 16,  15,  94,  43,  37,  31],
        [ 12,   6,  74,  29,  31,  18]],

       [[ 36,  13, 171,  88,  34,  49],
        [ 21,   6, 111,  58,  33,  27],
        [ 21,   6, 104,  45,  36,  27],
        [ 20,   6,  70,  31,  27,  26],
        [ 19,   0,  80,  40,  32,  19],
        [ 15,   8, 112,  46,  37,  23]],

       [[ 26,   8, 119,  70,  37,  34],
        [ 23,   7,  92,  58,  37,  30],
        [ 22,   0,  91,  60,  37,  22],
        [ 21,   6, 136,  77,  31,  27],
        [ 17,   3,  92,  59,  35,  20],
        [ 16,   9,  76,  45,  35,  25]]])

assert_array_almost_equal(A, answer11,decimal=3,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 12. 슈팅 정확도

* `슈팅정확도`는 `유효슈팅`을 `슈팅`으로 나눈(/) 데이터입니다. table-3에 `슈팅정확도`열을 추가한 표를 만들어주세요

    $$슈팅정확도 = \frac{유효슈팅}{슈팅}$$
 
 
* 변경 과정

![Imgur](https://i.imgur.com/8dOeN9c.png)


정답 >>>
```python
np.array([[[22., 1., 87., 42., 36., 0.48275862],
        [22., 5., 93., 40., 36., 0.43010753],
        [22., 8., 135., 64., 38., 0.47407407],
        [21., 8., 117., 43., 33., 0.36752137],
        [16., 15., 94., 43., 37., 0.45744681],
        [12., 6., 74., 29., 31., 0.39189189]],

       [[36., 13., 171., 88., 34., 0.51461988],
        [21., 6., 111., 58., 33., 0.52252252],
        [21., 6., 104., 45., 36., 0.43269231],
        [20., 6., 70., 31., 27., 0.44285714],
        [19., 0., 80., 40., 32., 0.5],
        [15., 8., 112., 46., 37., 0.41071429]],

       [[26., 8., 119., 70., 37., 0.58823529],
        [23., 7., 92., 58., 37., 0.63043478],
        [22., 0., 91., 60., 37., 0.65934066],
        [21., 6., 136., 77., 31., 0.56617647],
        [17., 3., 92., 59., 35., 0.64130435],
        [16., 9., 76., 45., 35., 0.59210526]]])
```

In [34]:
# 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

player_data = np.stack((england, spain, italy))
player_data

array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer12`에 담아주세요

In [35]:
shooting = player_data[:,:,2]
effective_shooting = player_data[:,:,3]
shooting_accuracy = effective_shooting / shooting
reshaped_shooting_accuracy = shooting_accuracy[...,None]
answer12 = np.concatenate((player_data, reshaped_shooting_accuracy),
                          axis=-1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [36]:
from numpy.testing import assert_array_almost_equal

assert 'answer12' in globals(), "결과를 answer12라는 변수에 담아주세요!, answer12의 값을 보고 평가합니다."

A = np.array([[[22., 1., 87., 42., 36., 0.48275862],
        [22., 5., 93., 40., 36., 0.43010753],
        [22., 8., 135., 64., 38., 0.47407407],
        [21., 8., 117., 43., 33., 0.36752137],
        [16., 15., 94., 43., 37., 0.45744681],
        [12., 6., 74., 29., 31., 0.39189189]],

       [[36., 13., 171., 88., 34., 0.51461988],
        [21., 6., 111., 58., 33., 0.52252252],
        [21., 6., 104., 45., 36., 0.43269231],
        [20., 6., 70., 31., 27., 0.44285714],
        [19., 0., 80., 40., 32., 0.5],
        [15., 8., 112., 46., 37., 0.41071429]],

       [[26., 8., 119., 70., 37., 0.58823529],
        [23., 7., 92., 58., 37., 0.63043478],
        [22., 0., 91., 60., 37., 0.65934066],
        [21., 6., 136., 77., 31., 0.56617647],
        [17., 3., 92., 59., 35., 0.64130435],
        [16., 9., 76., 45., 35., 0.59210526]]])

assert_array_almost_equal(A, answer12,decimal=4,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, DoYeong Kim ( ka2k@publicai.co.kr )  last updated on 2019/07/12
</div>
<hr>