## Numpy의 주요 함수들(2)


In [1]:
# 우선 실행해주세요
import numpy as np

### 문제 1. Min-Max Normalization

우리는 데이터를 다룰 때 주어진 데이터를 수정하는 `데이터 전처리` 과정을 꼭 거쳐야 합니다. 그 이유는 주어진 데이터들은 다른점들이 너무 많기 때문입니다. 예를 들어 키와 몸무게를 가지고 100m달리기에 걸리는 시간을 예측한다고 하면, 키와 몸무게는 `단위`가 다르기 때문에, 더 큰 값을 가진 키 값이 결과값에 더 큰 영향을 미칠 수도 있는 것입니다. 이러한 문제 때문에 우리는 전처리 과정이 필요합니다. 다양한 데이터 전처리 기법들이 있지만, 문제 1번에서는 **min-max normalization**을 다룰 것입니다. 

**min-max normalization**이란 데이터의 최댓값과 최솟값을 알 때, 데이터를 일반적으로 0~1 사이의 값으로 변환시켜주는 기법입니다. **min-max normalization**을 수행하는 수식은 다음과 같습니다.

$$x_{norm}~=~\frac{x-x_{min}}{x_{max}-x_{min}}$$

**min-max normalization**의 예시를 살펴보겠습니다. 아래와 같은 표에서 골과 슈팅정확도간의 상관관계가 궁금한 경우,

* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 | 슈팅정확도 |
|  ----   | --- |---| --- | --- | --- | --- |
| 스페인1등 |25 |13 |171 | 78 | 34 | 0.45614035 |
| 스페인2등 |21 |6 |131 | 58 | 33 | 0.44274809 |
| 스페인3등 |21 |6 |104 | 45 | 36 | 0.43269231 |
| 스페인4등 |20 |6 |70 | 30 | 27 | 0.4285714 |
| 스페인5등 |19 |0 |90 | 38 | 32 | 0.42222222 |
| 스페인6등 |15 |8 |112 | 46 | 37 | 0.41071429 |

전처리과정 없이 위의 표를 토대로 (골, 슈팅정확도)의 정도를 그래프로 나타내면 아래와 같습니다.

![Imgur](https://i.imgur.com/gK4Y4vOl.png)

보면 알 수 있듯이 골과 슈팅정확도는 대략 50배 정도 차이가 나서 슈팅정확도로 무언가를 구분하거나 슈팅정확도로부터 정보를 얻어내는 것이 쉽지 않아 보입니다. 골과 슈팅정확도를 둘다 `min=0, max=1`이 되도록 해서 값들을 0과 1사이로 맞추는 **min-max normalization**을 해준 후 (골, 슈팅정확도)의 그래프를 그리면 아래와 같습니다.

![Imgur](https://i.imgur.com/aKmk1Ajl.png)

골과 슈팅정확도가 같은 범위의 값으로 정렬되어 같은 영향력을 가지게 되니 골과 슈팅정확도간의 상관관계가 눈에 띄게 명확해 진 것을 확인할 수 있습니다.


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 | 슈팅정확도 |
|  ----   | --- |---| --- | --- | --- | --- |
| 스페인1등 |25 |13 |171 | 78 | 34 | 0.45614035 |
| 스페인2등 |21 |6 |131 | 58 | 33 | 0.44274809 |
| 스페인3등 |21 |6 |104 | 45 | 36 | 0.43269231 |
| 스페인4등 |20 |6 |70 | 30 | 27 | 0.4285714 |
| 스페인5등 |19 |0 |90 | 38 | 32 | 0.42222222 |
| 스페인6등 |15 |8 |112 | 46 | 37 | 0.41071429 |

* 위의 데이터에서 골과 슈팅정확도 데이터를 min-max normalization 한 후의 (골, 슈팅정확도) 데이터를 담고 있는 표를 만들어주세요

정답 >>>
```python
np.array([[1.        , 1.        ],
       [0.6       , 0.70518553],
       [0.6       , 0.48381964],
       [0.5       , 0.39310277],
       [0.4       , 0.25333322],
       [0.        , 0.        ]])
```

In [54]:
# 우선 실행해주세요
spain = np.array([[25, 13, 171,78,34,0.45614035],
[21, 6 , 131,58,33,0.44274809],
[21, 6 , 104,45,36,0.43269231],
[20, 6 , 70 ,30,27,0.4285714],
[19, 0 , 90 ,38,32,0.42222222],
[15, 8 , 112,46,37,0.41071429],])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer1`에 담아주세요

In [68]:
norm_spain = ((spain - spain.min(axis=0,keepdims=True)) 
              / (spain.max(axis=0,keepdims=True) - spain.min(axis=0,keepdims=True)))
answer1 = norm_spain[:,[0,-1]]

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [73]:
from numpy.testing import assert_array_almost_equal

assert 'answer1' in globals(), "결과를 answer1이라는 변수에 담아주세요!, answer1의 값을 보고 평가합니다."

A = np.array([[1.        , 1.        ],
       [0.6       , 0.70518553],
       [0.6       , 0.48381964],
       [0.5       , 0.39310277],
       [0.4       , 0.25333322],
       [0.        , 0.        ]])

assert_array_almost_equal(A,answer1,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


> 문제 2번, 문제 3번, 문제 4번, 문제 5번은 table-1을 참고하며 풀어주세요!



#### table-1) 학생들의 중간고사, 기말고사 성적표 

* 중간고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |80 |92 |70 | 65 | 92 |
|1 |91 |75 |90 | 68 | 85 | 
|2 |86 |76 |42 | 72 | 88 |
|3 |77 |92 |52 | 60 | 80 |
|4 |75 |85 |85 | 92 | 95 |
|5 |96 |90 |95 | 81 | 72 |


* 기말고사, 학생들의 국영수사과 성적표

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|0 |85 |95 |90 | 66 | 93 |
|1 |93 |70 |80 | 60 | 81 | 
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |
|4 |70 |82 |81 | 95 | 72 |
|5 |90 |76 |93 | 82 | 89 |

In [5]:
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores,final_scores])

scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

현재 데이터의 shape는 (2,6,5)로, 

* 첫번째 축 : 중간 / 기말
* 두번째 축 : 학생 번호 
* 세번째 축 : 과목

으로 구성되어 있다.

## 문제 2. 평균 구하기(1)
* **중간고사** 때, **국어, 영어, 수학** 의 학생 평균 성적은 계산해주세요.

정답 >>> 
```python
[84.16666667, 85.        , 72.33333333] # [국어, 영어, 수학]
```

In [6]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer2`에 담아주세요

In [7]:
answer2 = scores[0,:,:3].mean(axis=0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [8]:
from numpy.testing import assert_almost_equal

assert 'answer2' in globals(), "결과를 answer2라는 변수에 담아주세요!, answer2의 값을 보고 평가합니다."

A = [84.16666667, 85. , 72.33333333]

assert_almost_equal(A, answer2,decimal=3,
               err_msg="\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요\n".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 3. 차이의 평균 구하기
* **중간고사** 대비 **기말고사** 때의 성적 차이를 구하고, 과목 별 성적 차이의 평균을 구해주세요!

정답 >>>

```python
[0.33333333, -2.5, 4., 2., -1.16666667] # [국어,영어,수학,사회,과학]
```

In [9]:
# 우선 실행해주세요
scores = np.stack([middle_scores, final_scores])
scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer3`에 담아주세요

In [10]:
diff_scores = scores[1] - scores[0]
answer3 = diff_scores.mean(axis=0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [11]:
from numpy.testing import assert_almost_equal

assert 'answer3' in globals(), "결과를 answer3이라는 변수에 담아주세요!, answer3의 값을 보고 평가합니다."

A = [ 0.333, -2.5 ,4. ,  2. , -1.16666]

assert_almost_equal(A, answer3,decimal=3,
                    err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 4. 표준 점수 구하기
* 표준 점수는 아래와 같은 수식을 따른다. **중간고사** 때의 성적을 표준점수로 환산해주세요

$$
z = \frac{x-\mu}{\sigma}
$$


주의사항 
* 과목 별로 평균과 표준편차를 따로 구해 적용해야 합니다.


정답 >>>

```python
# 표준점수로 환산한 결과는 아래처럼 나옵니다
[[-0.55121733,  0.9834151 , -0.11852496, -0.74926865,  0.87121368],
       [ 0.90399642, -1.40487872,  0.89740324, -0.46829291, -0.04356068],
       [ 0.24253563, -1.26439085, -1.54082442, -0.09365858,  0.34848547],
       [-0.94809381,  0.9834151 , -1.03286033, -1.21756156, -0.69697095],
       [-1.21267813,  0.        ,  0.64342119,  1.77951304,  1.26325984],
       [ 1.56545722,  0.70243936,  1.15138528,  0.74926865, -1.74242737]]
```

In [12]:
# 우선 실행해주세요
middle_scores

array([[80, 92, 70, 65, 92],
       [91, 75, 90, 68, 85],
       [86, 76, 42, 72, 88],
       [77, 92, 52, 60, 80],
       [75, 85, 85, 92, 95],
       [96, 90, 95, 81, 72]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer4`에 담아주세요

In [13]:
subject_mean = middle_scores.mean(axis=0) #과목별 평균
subject_std = middle_scores.std(axis=0) #과목별 표준편차
answer4 = (middle_scores - subject_mean) / subject_std

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [14]:
from numpy.testing import assert_almost_equal

assert 'answer4' in globals(), "결과를 answer4라는 변수에 담아주세요!, answer4의 값을 보고 평가합니다."

A = [[-0.55121733,  0.9834151 , -0.11852496, -0.74926865,  0.87121368],
       [ 0.90399642, -1.40487872,  0.89740324, -0.46829291, -0.04356068],
       [ 0.24253563, -1.26439085, -1.54082442, -0.09365858,  0.34848547],
       [-0.94809381,  0.9834151 , -1.03286033, -1.21756156, -0.69697095],
       [-1.21267813,  0.        ,  0.64342119,  1.77951304,  1.26325984],
       [ 1.56545722,  0.70243936,  1.15138528,  0.74926865, -1.74242737]]

assert_almost_equal(A, answer4,decimal=3,err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))
print("정답입니다!!!")

정답입니다!!!


## 문제 5. 중간고사의 평균이 높은 순서대로 기말고사 정렬하기

* 중간고사의 평균이 높을 수록 기말고사 성젹표에서 학생이 위에 오도록 정렬된 기말고사 표를 만들어주세요

| 학생 번호 | 국어 | 영어 | 수학 | 사회 | 과학 |
|  ----   | --- |---| --- | --- | --- |
|5 |90 |76 |93 | 82 | 89 |
|4 |70 |82 |81 | 95 | 72 |
|1 |93 |70 |80 | 60 | 81 |
|0 |85 |95 |90 | 66 | 93 |
|2 |89 |78 |55 | 75 | 80 |
|3 |80 |94 |59 | 72 | 90 |


* 변경 과정

![Imgur](https://i.imgur.com/xWmdvCzl.png)

정답 >>>
```python
np.array([[90, 76, 93, 82, 89],
       [70, 82, 81, 95, 72],
       [93, 70, 80, 60, 81],
       [85, 95, 90, 66, 93],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90]])
```

In [15]:
# 우선 실행해주세요
middle_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])

scores = np.stack([middle_scores,final_scores])

scores

array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer5`에 담아주세요

In [16]:
middle_mean_score = middle_scores.mean(axis=1)
sorted_idx = middle_mean_score.argsort()
answer5 = final_scores[sorted_idx][::-1]

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [17]:
from numpy.testing import assert_array_almost_equal

assert 'answer5' in globals(), "결과를 answer5라는 변수에 담아주세요!, answer5의 값을 보고 평가합니다."

A = np.array([[90, 76, 93, 82, 89],
       [70, 82, 81, 95, 72],
       [93, 70, 80, 60, 81],
       [85, 95, 90, 66, 93],
       [89, 78, 55, 75, 80],
       [80, 94, 59, 72, 90]])

assert_array_almost_equal(A,answer5,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


> 문제 6번, 7번은 지난 exercise1에 있던 예제들입니다. list가 아닌 numpy로 풀어보세요!

#### table-2) 2012년~2018년 삼성전자 분기별 매출

| (단위:조원) | 1분기 | 2분기 | 3분기 | 4분기 |
| ------ | ----- | ----- | ----- | ----- |
| 2012년 | 45.27 | 47.60 | 52.18 | 56.06 |
| 2013년 | 52.87 | 57.46 | 59.08 | 59.28 |
| 2014년 | 53.68 | 52.35 | 47.45 | 52.73 |
| 2015년 | 47.12 | 48.54 | 51.68 | 53.32 |
| 2016년 | 49.78 | 50.94 | 47.82 | 53.33 |
| 2017년 | 50.55 | 61.99 | 62.05 | 65.98 |
| 2018년 | 60.56 | 58.48 | 65.46 | 59.27 |

## 문제 6. 모든 매출의 평균
* 삼성전자의 **모든 매출의 평균**을 가져와주세요.

정답 >>> 
```python
54.38857142857143
```

In [18]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer6`에 담아주세요

In [19]:
answer6 = sales.mean()

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [20]:
assert 'answer6' in globals(), "결과를 answer6이라는 변수에 담아주세요!, answer6의 값을 보고 평가합니다."

if (round(answer6, 5) == round(54.38857142857143, 5)):
    print("정답입니다!!!!")
else:
    raise ValueError("정답은 54.38857142857143가 나와야 합니다. 코드를 다시 확인해주세요!")

정답입니다!!!!


## 문제 7. 연도별 최대 매출
* 각 연도별로 최대 매출이 얼마인지 표로 만들어주세요

정답 >>> 
```python
np.array([56.06, 59.28, 53.68, 53.32, 53.33, 65.98, 65.46])
```

In [21]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer7`에 담아주세요

In [22]:
answer7 = sales.max(axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [23]:
from numpy.testing import assert_array_almost_equal

assert 'answer7' in globals(), "결과를 answer7이라는 변수에 담아주세요!, answer7의 값을 보고 평가합니다."

A = np.array([56.06, 59.28, 53.68, 53.32, 53.33, 65.98, 65.46])

assert_array_almost_equal(A,answer7,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 8. 분기별 평균

* 각 분기별 평균을 표로 만들어주세요

정답 >>>
```python
np.array([51.40428571, 53.90857143, 55.10285714, 57.13857143])
```

In [24]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer8`에 담아주세요

In [25]:
answer8 = sales.mean(axis=0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [26]:
from numpy.testing import assert_array_almost_equal

assert 'answer8' in globals(), "결과를 answer8이라는 변수에 담아주세요!, answer8의 값을 보고 평가합니다."

A = np.array([51.40428571, 53.90857143, 55.10285714, 57.13857143])

assert_array_almost_equal(A,answer8,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 9. 평균 대비 매출의 연도별 평균

* 평균 대비 매출의 연도별 평균을 표로 만들어주세요

    `평균 대비 매출` = `매출` - `전체 매출의 평균`
    
정답 >>>
```python
np.array([-4.11107143,  2.78392857, -2.83607143, -4.22357143,
          -3.92107143,  5.75392857,  6.55392857])
```

In [27]:
# 우선 실행해주세요
sales = np.array([
    [45.27, 47.60, 52.18, 56.06],
    [52.87, 57.46, 59.08, 59.28],
    [53.68, 52.35, 47.45, 52.73],
    [47.12, 48.54, 51.68, 53.32],
    [49.78, 50.94, 47.82, 53.33],
    [50.55, 61.99, 62.05, 65.98],
    [60.56, 58.48, 65.46, 59.27]
])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer9`에 담아주세요

In [41]:
num_year, num_period = sales.shape
average_sales = sales.sum() / (num_year * num_period)
wanted_sales = sales - average_sales
answer9 = wanted_sales.mean(axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [29]:
from numpy.testing import assert_array_almost_equal

assert 'answer9' in globals(), "결과를 answer9라는 변수에 담아주세요!, answer9의 값을 보고 평가합니다."

A = np.array([-4.11107143,  2.78392857, -2.83607143, -4.22357143,
          -3.92107143,  5.75392857,  6.55392857])

assert_array_almost_equal(A,answer9,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


> 문제 10번, 문제 11번, 문제 12번은 table-3을 참고하여 풀어주세요!

#### table-3) 득점순위에 따른 리그별 축구선수들의 데이터

* 영국리그 선수들의 데이터

| 영국 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국1등 |22 |1 |87 | 42 | 36 |
| 영국2등 |22 |5 |93 | 40 | 36 | 
| 영국3등 |22 |8 |135 | 64 | 38 |
| 영국4등 |21 |8 |117 | 43 | 33 |
| 영국5등 |16 |15 |94 | 43 | 37 |
| 영국6등 |12 |6 |74 | 29 | 31 |


* 스페인리그 선수들의 데이터

| 스페인 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 스페인1등 |36 |13 |171 | 88 | 34 |
| 스페인2등 |21 |6 |111 | 58 | 33 | 
| 스페인3등 |21 |6 |104 | 45 | 36 |
| 스페인4등 |20 |6 |70 | 31 | 27 |
| 스페인5등 |19 |0 |80 | 40 | 32 |
| 스페인6등 |15 |8 |112 | 46 | 37 |

* 이탈리아리그 선수들의 데이터

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 이탈리아1등 |26 |8 |119 | 70 | 37 |
| 이탈리아2등 |23 |7 |92 | 58 | 37 | 
| 이탈리아3등 |22 |0 |91 | 60 | 37 |
| 이탈리아4등 |21 |6 |136 | 77 | 31 |
| 이탈리아5등 |17 |3 |92 | 59 | 35 |
| 이탈리아6등 |16 |9 |76 | 45 | 35 |

## 문제 10. 선수들의 평균 데이터를 리그별로 비교하기

* 각 리그별로 1등~6등의 데이터를 평균낸뒤, 리그별로 볼 수 있는 표를 만들어주세요

| 리그별비교 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 영국평균 |19.16666667 |7.16666667 |100. | 43.5 | 35.16666667 |
| 스페인평균 |22. |6.5 |108. | 51.33333333 | 33.16666667 | 
| 이탈리아평균 |20.83333333 |5.5 |101. | 61.5 | 35.33333333 |

정답 >>>
```python
np.array([[ 19.16666667, 7.16666667, 100., 43.5, 35.16666667],
       [ 22., 6.5, 108., 51.33333333, 33.16666667],
       [ 20.83333333, 5.5, 101., 61.5, 35.33333333]])
```

In [30]:
## 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

player_data = np.stack((england, spain, italy))
player_data

array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer10`에 담아주세요

In [31]:
answer10 = player_data.mean(axis=1)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [32]:
from numpy.testing import assert_array_almost_equal

assert 'answer10' in globals(), "결과를 answer10이라는 변수에 담아주세요!, answer10의 값을 보고 평가합니다."

A = np.array([[ 19.16666667, 7.16666667, 100., 43.5, 35.16666667],
       [ 22., 6.5, 108., 51.33333333, 33.16666667],
       [ 20.83333333, 5.5, 101., 61.5, 35.33333333]])

assert_array_almost_equal(A,answer10,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 11. 선수들의 평균 데이터를 등수별로 비교하기

* 각 등수별로 데이터의 평균을 구한 후, 데이터를 등수별로 볼 수 있는 표를 만들어주세요

| 이탈리아 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 1등들의 평균 |28. |7.33333333 |125.66666667 | 66.66666667 | 35.66666667 |
| 2등들의 평균 |22. |6. |98.66666667 | 52. | 35.33333333 |
| 3등들의 평균 |21.66666667 |4.66666667 |110. | 56.33333333 | 37.|
| 4등들의 평균 |20.66666667 |6.66666667 |107.66666667 | 50.33333333 | 30.33333333 |
| 5등들의 평균 |17.33333333 |6. | 88.66666667 | 47.33333333 | 34.66666667 |
| 6등들의 평균 |14.33333333 |7.66666667 |87.33333333 | 40. | 34.33333333 |

정답 >>>
```python
np.array([[ 28., 7.33333333, 125.66666667, 66.66666667, 35.66666667],
       [ 22., 6., 98.66666667, 52., 35.33333333],
       [ 21.66666667, 4.66666667, 110. ,56.33333333, 37.],
       [ 20.66666667, 6.66666667, 107.66666667,50.33333333, 30.33333333],
       [ 17.33333333, 6. , 88.66666667,47.33333333, 34.66666667],
       [ 14.33333333, 7.66666667, 87.33333333, 40.,34.33333333]])
```

In [33]:
## 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

player_data = np.stack((england, spain, italy))
player_data

array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer11`에 담아주세요

In [34]:
answer11 = player_data.mean(axis=0)

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [35]:
from numpy.testing import assert_array_almost_equal

assert 'answer11' in globals(), "결과를 answer11이라는 변수에 담아주세요!, answer11의 값을 보고 평가합니다."

A = np.array([[ 28., 7.33333333, 125.66666667, 66.66666667, 35.66666667],
       [ 22., 6., 98.66666667, 52., 35.33333333],
       [ 21.66666667, 4.66666667, 110. ,56.33333333, 37.],
       [ 20.66666667, 6.66666667, 107.66666667,50.33333333, 30.33333333],
       [ 17.33333333, 6. , 88.66666667,47.33333333, 34.66666667],
       [ 14.33333333, 7.66666667, 87.33333333, 40.,34.33333333]])

assert_array_almost_equal(A,answer11,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


## 문제 12. 전체 선수들의 평균 데이터

* 전체 선수들의 각 데이터의 평균을 담고 있는 표를 만들어주세요

| 평균데이터 | 골 | 도움 | 슈팅 | 유효슈팅 | 경기수 |
|  ----   | --- |---| --- | --- | --- |
| 전체평균 |20.66666667 |6.38888889 |103. | 52.11111111 | 34.55555556 |

정답 >>>
```python
np.array([ 20.66666667, 6.38888889, 103., 52.11111111, 34.55555556])
```

In [36]:
## 우선 입력해주세요
england = np.array([
    [22,1,87,42,36],
    [22,5,93,40,36],
    [22,8,135,64,38],
    [21,8,117,43,33],
    [16,15,94,43,37],
    [12,6,74,29,31]
])

spain = np.array([
    [36,13,171,88,34],
    [21,6,111,58,33],
    [21,6,104,45,36],
    [20,6,70,31,27],
    [19,0,80,40,32],
    [15,8,112,46,37]
])

italy = np.array([
    [26,8,119,70,37],
    [23,7,92,58,37],
    [22,0,91,60,37],
    [21,6,136,77,31],
    [17,3,92,59,35],
    [16,9,76,45,35]
])

player_data = np.stack((england, spain, italy))
player_data

array([[[ 22,   1,  87,  42,  36],
        [ 22,   5,  93,  40,  36],
        [ 22,   8, 135,  64,  38],
        [ 21,   8, 117,  43,  33],
        [ 16,  15,  94,  43,  37],
        [ 12,   6,  74,  29,  31]],

       [[ 36,  13, 171,  88,  34],
        [ 21,   6, 111,  58,  33],
        [ 21,   6, 104,  45,  36],
        [ 20,   6,  70,  31,  27],
        [ 19,   0,  80,  40,  32],
        [ 15,   8, 112,  46,  37]],

       [[ 26,   8, 119,  70,  37],
        [ 23,   7,  92,  58,  37],
        [ 22,   0,  91,  60,  37],
        [ 21,   6, 136,  77,  31],
        [ 17,   3,  92,  59,  35],
        [ 16,   9,  76,  45,  35]]])

#### 답안지 입력란
* 아래에 답을 서술하여 주세요
* 결과는 `answer12`에 담아주세요

In [37]:
answer12 = player_data.mean(axis=(0,1))

#### 정답 확인
* 정답을 입력한 후, 아래를 실행시키면 정답인지 확인합니다.

In [38]:
from numpy.testing import assert_array_almost_equal

assert 'answer12' in globals(), "결과를 answer12라는 변수에 담아주세요!, answer12의 값을 보고 평가합니다."

A = np.array([ 20.66666667, 6.38888889, 103., 52.11111111, 34.55555556])

assert_array_almost_equal(A,answer12,decimal=2,
                          err_msg="\n\n정답은 \n{}\n입니다. 코드를 다시 확인해주세요".format(A))

print("정답입니다!!!")

정답입니다!!!


#  

<hr>
<div style = "background-image: url('https://algorithmai.io/static/media/logo.665798c4.png');background-repeat: no-repeat; background-position: right; background-size: 220px 40px; padding : 5px 10px 5px 5px;">
    Copyright(c) 2019 by Public AI. All rights reserved.<br>
    Writen by PAI, DoYeong Kim ( ka2k@publicai.co.kr )  last updated on 2019/07/12
</div>
<hr>